apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "course-app.fullname" . }}
  labels:
    app: {{ include "course-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "course-app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "course-app.fullname" . }}
    spec:
      containers:
        - name: web-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP